const express=require('express');const multer=require('multer');const path=require('path');const fs=require('fs');const pdfParse=require('pdf-parse');const mammoth=require('mammoth');
const app=express();const PORT=process.env.PORT||3000;const uploads=path.join(__dirname,'uploads');fs.mkdirSync(uploads,{recursive:true});
app.use(express.json({limit:'12mb'}));app.use(express.urlencoded({extended:true,limit:'12mb'}));app.use(express.static(path.join(__dirname,'public')));
const upload=multer({dest:uploads,limits:{fileSize:12*1024*1024}});
async function gemini(model,contents,responseModalities){const key=process.env.GEMINI_API_KEY;if(!key)throw Error('GEMINI_API_KEY is not configured.');const body={contents};if(responseModalities)body.generationConfig={responseModalities};const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d?.error?.message||`Gemini API error ${r.status}`);return d}
const text=d=>(d?.candidates?.[0]?.content?.parts||[]).filter(p=>typeof p.text==='string').map(p=>p.text).join('\n');
const imgs=d=>(d?.candidates?.[0]?.content?.parts||[]).filter(p=>p.inlineData?.data).map(p=>({mimeType:p.inlineData.mimeType||'image/png',data:p.inlineData.data}));
function route(s,file){s=String(s||'').toLowerCase();if(file)return'file-agent';if(/(generate|create|draw|make).*(image|photo|picture)|image.*generate|create.*photo/.test(s))return'image-agent';if(/(edit|change|remove|replace|enhance).*(image|photo|background)/.test(s))return'edit-agent';if(/(code|bug|error|debug|javascript|python|java|html|css|program)/.test(s))return'coding-agent';return'chat-agent'}
app.get('/api/health',(q,r)=>r.json({ok:true,name:'NOVA AI',aiConfigured:!!process.env.GEMINI_API_KEY}));
app.post('/api/chat',async(req,res)=>{try{const m=String(req.body.message||'').trim();if(!m)return res.status(400).json({error:'Message is required.'});const history=Array.isArray(req.body.history)?req.body.history.slice(-12):[];const agent=route(m,false);const contents=[{role:'user',parts:[{text:`You are NOVA AI, a practical all-rounder assistant. Be accurate and direct. Answer in Tamil, English, or Tanglish when requested. Do not pretend to have generated files or images. Specialist route: ${agent}.`} ]},...history.filter(x=>x&&(x.role==='user'||x.role==='model')&&typeof x.text==='string').map(x=>({role:x.role,parts:[{text:x.text}]})),{role:'user',parts:[{text:m}]}];const d=await gemini(process.env.GEMINI_TEXT_MODEL||'gemini-2.5-flash',contents);res.json({ok:true,agent,text:text(d)||'No response returned.'})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/image/generate',async(req,res)=>{try{const p=String(req.body.prompt||'').trim();if(!p)return res.status(400).json({error:'Image prompt is required.'});const d=await gemini(process.env.GEMINI_IMAGE_MODEL||'gemini-2.5-flash-image',[{role:'user',parts:[{text:`Create a high-quality image based on this request. ${p}`}]}],['TEXT','IMAGE']);res.json({ok:true,text:text(d),images:imgs(d)})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/image/edit',upload.single('image'),async(req,res)=>{let fp;try{if(!req.file)return res.status(400).json({error:'Please upload an image.'});const ins=String(req.body.instruction||'').trim();if(!ins)return res.status(400).json({error:'Edit instruction is required.'});fp=req.file.path;const b=fs.readFileSync(fp);const d=await gemini(process.env.GEMINI_IMAGE_MODEL||'gemini-2.5-flash-image',[{role:'user',parts:[{inlineData:{mimeType:req.file.mimetype,data:b.toString('base64')}},{text:`Edit this image according to the instruction. Preserve important subject details unless asked otherwise. Instruction: ${ins}`}]}],['TEXT','IMAGE']);res.json({ok:true,text:text(d),images:imgs(d)})}catch(e){res.status(500).json({error:e.message})}finally{if(fp)fs.unlink(fp,()=>{})}});
async function extract(f){const ext=path.extname(f.originalname).toLowerCase(),b=fs.readFileSync(f.path);if(ext==='.pdf')return(await pdfParse(b)).text;if(ext==='.docx')return(await mammoth.extractRawText({buffer:b})).value;if(['.txt','.md','.csv','.json','.js','.py','.java','.html','.css'].includes(ext))return b.toString('utf8');if(f.mimetype.startsWith('image/'))return null;return b.toString('utf8')}
app.post('/api/file/analyze',upload.single('file'),async(req,res)=>{let fp;try{if(!req.file)return res.status(400).json({error:'Please upload a file.'});fp=req.file.path;const q=String(req.body.question||'Summarize this file and list important points.');const t=await extract(req.file);let d;if(t===null){const b=fs.readFileSync(fp);d=await gemini(process.env.GEMINI_TEXT_MODEL||'gemini-2.5-flash',[{role:'user',parts:[{inlineData:{mimeType:req.file.mimetype,data:b.toString('base64')}},{text:q}]}])}else{d=await gemini(process.env.GEMINI_TEXT_MODEL||'gemini-2.5-flash',[{role:'user',parts:[{text:`You are NOVA File Agent. Analyze this document. User request: ${q}\n\nDOCUMENT:\n${t.slice(0,90000)}`}]}])}res.json({ok:true,agent:'file-agent',text:text(d),truncated:t&&t.length>90000})}catch(e){res.status(500).json({error:e.message})}finally{if(fp)fs.unlink(fp,()=>{})}});
app.post('/api/voice/text',async(req,res)=>{try{const m=String(req.body.message||'').trim();if(!m)return res.status(400).json({error:'Voice transcript is empty.'});const d=await gemini(process.env.GEMINI_TEXT_MODEL||'gemini-2.5-flash',[{role:'user',parts:[{text:m}]}]);res.json({ok:true,text:text(d)})}catch(e){res.status(500).json({error:e.message})}});
app.get('*',(q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,'0.0.0.0',()=>console.log(`NOVA AI running on port ${PORT}`));
